/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_GDaffiche (void)
{
  GtkWidget *GDaffiche;
  GtkWidget *fixed1;
  GtkWidget *treeviewGD;
  GtkWidget *GDsearchEntry;
  GtkWidget *GDajoutWidget;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *GDmodifierWidget;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *GDsupprimerWidget;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *GDactualiser;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *GDstatistiqueWidget;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label7;
  GtkWidget *GDsearchButton;
  GtkWidget *image1;
  GtkWidget *GDdeconnexcion;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *label1;

  GDaffiche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (GDaffiche, 990, 801);
  gtk_window_set_title (GTK_WINDOW (GDaffiche), _("Gestion Des demandes"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (GDaffiche), fixed1);
  gtk_widget_set_size_request (fixed1, 939, 754);

  treeviewGD = gtk_tree_view_new ();
  gtk_widget_show (treeviewGD);
  gtk_fixed_put (GTK_FIXED (fixed1), treeviewGD, 200, 240);
  gtk_widget_set_size_request (treeviewGD, 568, 448);

  GDsearchEntry = gtk_entry_new ();
  gtk_widget_show (GDsearchEntry);
  gtk_fixed_put (GTK_FIXED (fixed1), GDsearchEntry, 376, 176);
  gtk_widget_set_size_request (GDsearchEntry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (GDsearchEntry), 8226);

  GDajoutWidget = gtk_button_new ();
  gtk_widget_show (GDajoutWidget);
  gtk_fixed_put (GTK_FIXED (fixed1), GDajoutWidget, 0, 0);
  gtk_widget_set_size_request (GDajoutWidget, 144, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (GDajoutWidget), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  GDmodifierWidget = gtk_button_new ();
  gtk_widget_show (GDmodifierWidget);
  gtk_fixed_put (GTK_FIXED (fixed1), GDmodifierWidget, 144, 0);
  gtk_widget_set_size_request (GDmodifierWidget, 192, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (GDmodifierWidget), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Modification"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  GDsupprimerWidget = gtk_button_new ();
  gtk_widget_show (GDsupprimerWidget);
  gtk_fixed_put (GTK_FIXED (fixed1), GDsupprimerWidget, 336, 0);
  gtk_widget_set_size_request (GDsupprimerWidget, 184, 48);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (GDsupprimerWidget), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  GDactualiser = gtk_button_new ();
  gtk_widget_show (GDactualiser);
  gtk_fixed_put (GTK_FIXED (fixed1), GDactualiser, 520, 0);
  gtk_widget_set_size_request (GDactualiser, 192, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (GDactualiser), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  GDstatistiqueWidget = gtk_button_new ();
  gtk_widget_show (GDstatistiqueWidget);
  gtk_fixed_put (GTK_FIXED (fixed1), GDstatistiqueWidget, 712, 0);
  gtk_widget_set_size_request (GDstatistiqueWidget, 208, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (GDstatistiqueWidget), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Statistique"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox6), label7, FALSE, FALSE, 0);

  GDsearchButton = gtk_button_new ();
  gtk_widget_show (GDsearchButton);
  gtk_fixed_put (GTK_FIXED (fixed1), GDsearchButton, 576, 176);
  gtk_widget_set_size_request (GDsearchButton, 58, 29);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (GDsearchButton), image1);

  GDdeconnexcion = gtk_button_new ();
  gtk_widget_show (GDdeconnexcion);
  gtk_fixed_put (GTK_FIXED (fixed1), GDdeconnexcion, 424, 728);
  gtk_widget_set_size_request (GDdeconnexcion, 122, 45);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (GDdeconnexcion), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-media-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("Gestion Des demandes"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 384, 112);
  gtk_widget_set_size_request (label1, 193, 17);

  g_signal_connect ((gpointer) treeviewGD, "row_activated",
                    G_CALLBACK (on_treeviewGD_row_activated),
                    NULL);
  g_signal_connect ((gpointer) GDajoutWidget, "clicked",
                    G_CALLBACK (on_GDajoutWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDmodifierWidget, "clicked",
                    G_CALLBACK (on_GDmodifierWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDsupprimerWidget, "clicked",
                    G_CALLBACK (on_GDsupprimerWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDactualiser, "clicked",
                    G_CALLBACK (on_GDactualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDstatistiqueWidget, "clicked",
                    G_CALLBACK (on_GDstatistiqueWidget_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDsearchButton, "clicked",
                    G_CALLBACK (on_GDsearchButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDdeconnexcion, "clicked",
                    G_CALLBACK (on_GDdeconnexcion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDaffiche, GDaffiche, "GDaffiche");
  GLADE_HOOKUP_OBJECT (GDaffiche, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (GDaffiche, treeviewGD, "treeviewGD");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDsearchEntry, "GDsearchEntry");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDajoutWidget, "GDajoutWidget");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (GDaffiche, image3, "image3");
  GLADE_HOOKUP_OBJECT (GDaffiche, label3, "label3");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDmodifierWidget, "GDmodifierWidget");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (GDaffiche, image4, "image4");
  GLADE_HOOKUP_OBJECT (GDaffiche, label4, "label4");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDsupprimerWidget, "GDsupprimerWidget");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (GDaffiche, image5, "image5");
  GLADE_HOOKUP_OBJECT (GDaffiche, label5, "label5");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDactualiser, "GDactualiser");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (GDaffiche, image6, "image6");
  GLADE_HOOKUP_OBJECT (GDaffiche, label6, "label6");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDstatistiqueWidget, "GDstatistiqueWidget");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (GDaffiche, image7, "image7");
  GLADE_HOOKUP_OBJECT (GDaffiche, label7, "label7");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDsearchButton, "GDsearchButton");
  GLADE_HOOKUP_OBJECT (GDaffiche, image1, "image1");
  GLADE_HOOKUP_OBJECT (GDaffiche, GDdeconnexcion, "GDdeconnexcion");
  GLADE_HOOKUP_OBJECT (GDaffiche, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (GDaffiche, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (GDaffiche, image2, "image2");
  GLADE_HOOKUP_OBJECT (GDaffiche, label2, "label2");
  GLADE_HOOKUP_OBJECT (GDaffiche, label1, "label1");

  return GDaffiche;
}

GtkWidget*
create_GDsupprime (void)
{
  GtkWidget *GDsupprime;
  GtkWidget *fixed2;
  GtkWidget *GDidEntrySupprimer;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *GDcontroleSaisiSupprimer;
  GtkWidget *GDsupprimerButton;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label10;
  GtkWidget *GDannulerSupprimerButton;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label11;

  GDsupprime = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (GDsupprime, 486, 275);
  gtk_window_set_title (GTK_WINDOW (GDsupprime), _("Supprimer Des demandes"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (GDsupprime), fixed2);

  GDidEntrySupprimer = gtk_entry_new ();
  gtk_widget_show (GDidEntrySupprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), GDidEntrySupprimer, 168, 104);
  gtk_widget_set_size_request (GDidEntrySupprimer, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (GDidEntrySupprimer), 8226);

  label8 = gtk_label_new (_("ID"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 88, 112);
  gtk_widget_set_size_request (label8, 49, 17);

  label9 = gtk_label_new (_("Supprimer Des demandes"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 160, 48);
  gtk_widget_set_size_request (label9, 179, 17);

  GDcontroleSaisiSupprimer = gtk_label_new ("");
  gtk_widget_show (GDcontroleSaisiSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), GDcontroleSaisiSupprimer, 112, 160);
  gtk_widget_set_size_request (GDcontroleSaisiSupprimer, 300, 23);

  GDsupprimerButton = gtk_button_new ();
  gtk_widget_show (GDsupprimerButton);
  gtk_fixed_put (GTK_FIXED (fixed2), GDsupprimerButton, 264, 208);
  gtk_widget_set_size_request (GDsupprimerButton, 150, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (GDsupprimerButton), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox7), label10, FALSE, FALSE, 0);

  GDannulerSupprimerButton = gtk_button_new ();
  gtk_widget_show (GDannulerSupprimerButton);
  gtk_fixed_put (GTK_FIXED (fixed2), GDannulerSupprimerButton, 104, 208);
  gtk_widget_set_size_request (GDannulerSupprimerButton, 150, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (GDannulerSupprimerButton), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox8), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) GDsupprimerButton, "clicked",
                    G_CALLBACK (on_GDsupprimerButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDannulerSupprimerButton, "clicked",
                    G_CALLBACK (on_GDannulerSupprimerButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDsupprime, GDsupprime, "GDsupprime");
  GLADE_HOOKUP_OBJECT (GDsupprime, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (GDsupprime, GDidEntrySupprimer, "GDidEntrySupprimer");
  GLADE_HOOKUP_OBJECT (GDsupprime, label8, "label8");
  GLADE_HOOKUP_OBJECT (GDsupprime, label9, "label9");
  GLADE_HOOKUP_OBJECT (GDsupprime, GDcontroleSaisiSupprimer, "GDcontroleSaisiSupprimer");
  GLADE_HOOKUP_OBJECT (GDsupprime, GDsupprimerButton, "GDsupprimerButton");
  GLADE_HOOKUP_OBJECT (GDsupprime, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (GDsupprime, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (GDsupprime, image8, "image8");
  GLADE_HOOKUP_OBJECT (GDsupprime, label10, "label10");
  GLADE_HOOKUP_OBJECT (GDsupprime, GDannulerSupprimerButton, "GDannulerSupprimerButton");
  GLADE_HOOKUP_OBJECT (GDsupprime, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (GDsupprime, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (GDsupprime, image9, "image9");
  GLADE_HOOKUP_OBJECT (GDsupprime, label11, "label11");

  return GDsupprime;
}

GtkWidget*
create_GDajoute (void)
{
  GtkWidget *GDajoute;
  GtkWidget *fixed3;
  GtkWidget *GDidEntryAjout;
  GtkWidget *label13;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkObject *GDjjSpinAjout_adj;
  GtkWidget *GDjjSpinAjout;
  GtkObject *GDmmSpinAjout_adj;
  GtkWidget *GDmmSpinAjout;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkObject *GDyySpinAjout_adj;
  GtkWidget *GDyySpinAjout;
  GtkObject *GDquantiteSpinAjout_adj;
  GtkWidget *GDquantiteSpinAjout;
  GtkWidget *label24;
  GtkWidget *GDajoutButton;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label26;
  GtkWidget *label28;
  GtkWidget *label19;
  GtkWidget *GDnonUrgenceAjout;
  GSList *GDnonUrgenceAjout_group = NULL;
  GtkWidget *GDouiUrgenceAjout;
  GtkWidget *GDtypeSangComboAjout1;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *GDTraiteStatusAjout;
  GtkWidget *GDCoursStatusAjout;
  GtkWidget *label23;
  GtkWidget *GDannulerAjoutButton;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label25;
  GtkWidget *GDcontroleSaisiAjout;
  GtkWidget *GDetabComboAjout1;

  GDajoute = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (GDajoute, 891, 858);
  gtk_window_set_title (GTK_WINDOW (GDajoute), _("Ajout Demande"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (GDajoute), fixed3);

  GDidEntryAjout = gtk_entry_new ();
  gtk_widget_show (GDidEntryAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDidEntryAjout, 344, 144);
  gtk_widget_set_size_request (GDidEntryAjout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (GDidEntryAjout), 8226);

  label13 = gtk_label_new (_("ID"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 272, 152);
  gtk_widget_set_size_request (label13, 49, 17);

  label15 = gtk_label_new (_("etablissement"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 232, 248);
  gtk_widget_set_size_request (label15, 111, 17);

  label16 = gtk_label_new (_("Jour"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 296, 352);
  gtk_widget_set_size_request (label16, 49, 17);

  GDjjSpinAjout_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDjjSpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (GDjjSpinAjout_adj), 1, 0);
  gtk_widget_show (GDjjSpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDjjSpinAjout, 360, 344);
  gtk_widget_set_size_request (GDjjSpinAjout, 60, 27);

  GDmmSpinAjout_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDmmSpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (GDmmSpinAjout_adj), 1, 0);
  gtk_widget_show (GDmmSpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDmmSpinAjout, 536, 344);
  gtk_widget_set_size_request (GDmmSpinAjout, 60, 27);

  label17 = gtk_label_new (_("Mois"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 480, 352);
  gtk_widget_set_size_request (label17, 49, 17);

  label18 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 656, 352);
  gtk_widget_set_size_request (label18, 49, 17);

  GDyySpinAjout_adj = gtk_adjustment_new (2023, 1950, 2024, 1, 10, 10);
  GDyySpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (GDyySpinAjout_adj), 1, 0);
  gtk_widget_show (GDyySpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDyySpinAjout, 720, 344);
  gtk_widget_set_size_request (GDyySpinAjout, 60, 27);

  GDquantiteSpinAjout_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDquantiteSpinAjout = gtk_spin_button_new (GTK_ADJUSTMENT (GDquantiteSpinAjout_adj), 1, 0);
  gtk_widget_show (GDquantiteSpinAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDquantiteSpinAjout, 352, 200);
  gtk_widget_set_size_request (GDquantiteSpinAjout, 60, 27);

  label24 = gtk_label_new (_("Ajouter Demande"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 304, 72);
  gtk_widget_set_size_request (label24, 300, 17);

  GDajoutButton = gtk_button_new ();
  gtk_widget_show (GDajoutButton);
  gtk_fixed_put (GTK_FIXED (fixed3), GDajoutButton, 592, 752);
  gtk_widget_set_size_request (GDajoutButton, 219, 58);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (GDajoutButton), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox10), label26, FALSE, FALSE, 0);

  label28 = gtk_label_new (_("Quantite de Poche"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 200, 200);
  gtk_widget_set_size_request (label28, 136, 25);

  label19 = gtk_label_new (_("Date :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 208, 352);
  gtk_widget_set_size_request (label19, 72, 17);

  GDnonUrgenceAjout = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (GDnonUrgenceAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDnonUrgenceAjout, 472, 528);
  gtk_widget_set_size_request (GDnonUrgenceAjout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (GDnonUrgenceAjout), GDnonUrgenceAjout_group);
  GDnonUrgenceAjout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (GDnonUrgenceAjout));

  GDouiUrgenceAjout = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (GDouiUrgenceAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDouiUrgenceAjout, 344, 528);
  gtk_widget_set_size_request (GDouiUrgenceAjout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (GDouiUrgenceAjout), GDnonUrgenceAjout_group);
  GDnonUrgenceAjout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (GDouiUrgenceAjout));

  GDtypeSangComboAjout1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (GDtypeSangComboAjout1);
  gtk_fixed_put (GTK_FIXED (fixed3), GDtypeSangComboAjout1, 344, 440);
  gtk_widget_set_size_request (GDtypeSangComboAjout1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("A+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("A-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("B+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("B-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("O+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("O-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("AB+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboAjout1), _("AB-"));

  label21 = gtk_label_new (_("Type de Sang"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 200, 440);
  gtk_widget_set_size_request (label21, 112, 25);

  label22 = gtk_label_new (_("Cas d'urgence  :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 168, 528);
  gtk_widget_set_size_request (label22, 128, 25);

  GDTraiteStatusAjout = gtk_check_button_new_with_mnemonic (_("trait\303\251"));
  gtk_widget_show (GDTraiteStatusAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDTraiteStatusAjout, 488, 592);
  gtk_widget_set_size_request (GDTraiteStatusAjout, 118, 24);

  GDCoursStatusAjout = gtk_check_button_new_with_mnemonic (_("en cours"));
  gtk_widget_show (GDCoursStatusAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDCoursStatusAjout, 336, 592);
  gtk_widget_set_size_request (GDCoursStatusAjout, 118, 24);

  label23 = gtk_label_new (_("Statut de la demande :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 160, 584);
  gtk_widget_set_size_request (label23, 160, 33);

  GDannulerAjoutButton = gtk_button_new ();
  gtk_widget_show (GDannulerAjoutButton);
  gtk_fixed_put (GTK_FIXED (fixed3), GDannulerAjoutButton, 128, 744);
  gtk_widget_set_size_request (GDannulerAjoutButton, 219, 58);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (GDannulerAjoutButton), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox9), label25, FALSE, FALSE, 0);

  GDcontroleSaisiAjout = gtk_label_new ("");
  gtk_widget_show (GDcontroleSaisiAjout);
  gtk_fixed_put (GTK_FIXED (fixed3), GDcontroleSaisiAjout, 320, 664);
  gtk_widget_set_size_request (GDcontroleSaisiAjout, 300, 25);

  GDetabComboAjout1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (GDetabComboAjout1);
  gtk_fixed_put (GTK_FIXED (fixed3), GDetabComboAjout1, 360, 240);
  gtk_widget_set_size_request (GDetabComboAjout1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboAjout1), _("etab1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboAjout1), _("etab2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboAjout1), _("etab3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboAjout1), _("etab4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboAjout1), _("etab5"));

  g_signal_connect ((gpointer) GDajoutButton, "clicked",
                    G_CALLBACK (on_GDajoutButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDnonUrgenceAjout, "toggled",
                    G_CALLBACK (on_GDnonUrgenceAjout_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDouiUrgenceAjout, "toggled",
                    G_CALLBACK (on_GDouiUrgenceAjout_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDTraiteStatusAjout, "toggled",
                    G_CALLBACK (on_GDTraiteStatusAjout_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDCoursStatusAjout, "toggled",
                    G_CALLBACK (on_GDCoursStatusAjout_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDannulerAjoutButton, "clicked",
                    G_CALLBACK (on_GDannulerAjoutButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDajoute, GDajoute, "GDajoute");
  GLADE_HOOKUP_OBJECT (GDajoute, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (GDajoute, GDidEntryAjout, "GDidEntryAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, label13, "label13");
  GLADE_HOOKUP_OBJECT (GDajoute, label15, "label15");
  GLADE_HOOKUP_OBJECT (GDajoute, label16, "label16");
  GLADE_HOOKUP_OBJECT (GDajoute, GDjjSpinAjout, "GDjjSpinAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDmmSpinAjout, "GDmmSpinAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, label17, "label17");
  GLADE_HOOKUP_OBJECT (GDajoute, label18, "label18");
  GLADE_HOOKUP_OBJECT (GDajoute, GDyySpinAjout, "GDyySpinAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDquantiteSpinAjout, "GDquantiteSpinAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, label24, "label24");
  GLADE_HOOKUP_OBJECT (GDajoute, GDajoutButton, "GDajoutButton");
  GLADE_HOOKUP_OBJECT (GDajoute, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (GDajoute, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (GDajoute, image11, "image11");
  GLADE_HOOKUP_OBJECT (GDajoute, label26, "label26");
  GLADE_HOOKUP_OBJECT (GDajoute, label28, "label28");
  GLADE_HOOKUP_OBJECT (GDajoute, label19, "label19");
  GLADE_HOOKUP_OBJECT (GDajoute, GDnonUrgenceAjout, "GDnonUrgenceAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDouiUrgenceAjout, "GDouiUrgenceAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDtypeSangComboAjout1, "GDtypeSangComboAjout1");
  GLADE_HOOKUP_OBJECT (GDajoute, label21, "label21");
  GLADE_HOOKUP_OBJECT (GDajoute, label22, "label22");
  GLADE_HOOKUP_OBJECT (GDajoute, GDTraiteStatusAjout, "GDTraiteStatusAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDCoursStatusAjout, "GDCoursStatusAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, label23, "label23");
  GLADE_HOOKUP_OBJECT (GDajoute, GDannulerAjoutButton, "GDannulerAjoutButton");
  GLADE_HOOKUP_OBJECT (GDajoute, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (GDajoute, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (GDajoute, image10, "image10");
  GLADE_HOOKUP_OBJECT (GDajoute, label25, "label25");
  GLADE_HOOKUP_OBJECT (GDajoute, GDcontroleSaisiAjout, "GDcontroleSaisiAjout");
  GLADE_HOOKUP_OBJECT (GDajoute, GDetabComboAjout1, "GDetabComboAjout1");

  return GDajoute;
}

GtkWidget*
create_GDmodife (void)
{
  GtkWidget *GDmodife;
  GtkWidget *fixed4;
  GtkWidget *GDidEntryModifier;
  GtkWidget *label29;
  GtkWidget *label31;
  GtkObject *GDjjSpinModifier_adj;
  GtkWidget *GDjjSpinModifier;
  GtkObject *GDmmSpinModifier_adj;
  GtkWidget *GDmmSpinModifier;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkObject *GDyySpinModifier_adj;
  GtkWidget *GDyySpinModifier;
  GtkObject *GDquantiteSpinModifier_adj;
  GtkWidget *GDquantiteSpinModifier;
  GtkWidget *label35;
  GtkWidget *GDcontroleSaisiModifier;
  GtkWidget *GDtypeSangComboModifier1;
  GtkWidget *label40;
  GtkWidget *GDnonUrgenceModifier;
  GSList *GDnonUrgenceModifier_group = NULL;
  GtkWidget *GDouiUrgenceModifier;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *GDCoursStatusModifier;
  GtkWidget *GDTraiteStatusModifier;
  GtkWidget *label39;
  GtkWidget *label34;
  GtkWidget *GDetabComboModifier1;
  GtkWidget *label30;
  GtkWidget *GDannulerModifierButton;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label36;
  GtkWidget *GDModifierButton;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label37;

  GDmodife = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (GDmodife, 891, 858);
  gtk_window_set_title (GTK_WINDOW (GDmodife), _("Modifier Demande"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (GDmodife), fixed4);

  GDidEntryModifier = gtk_entry_new ();
  gtk_widget_show (GDidEntryModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDidEntryModifier, 344, 144);
  gtk_widget_set_size_request (GDidEntryModifier, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (GDidEntryModifier), 8226);

  label29 = gtk_label_new (_("ID"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 272, 152);
  gtk_widget_set_size_request (label29, 49, 17);

  label31 = gtk_label_new (_("Jour"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed4), label31, 296, 352);
  gtk_widget_set_size_request (label31, 49, 17);

  GDjjSpinModifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDjjSpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (GDjjSpinModifier_adj), 1, 0);
  gtk_widget_show (GDjjSpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDjjSpinModifier, 368, 344);
  gtk_widget_set_size_request (GDjjSpinModifier, 60, 27);

  GDmmSpinModifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDmmSpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (GDmmSpinModifier_adj), 1, 0);
  gtk_widget_show (GDmmSpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDmmSpinModifier, 536, 344);
  gtk_widget_set_size_request (GDmmSpinModifier, 60, 27);

  label32 = gtk_label_new (_("Mois"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 480, 352);
  gtk_widget_set_size_request (label32, 49, 17);

  label33 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 656, 352);
  gtk_widget_set_size_request (label33, 49, 17);

  GDyySpinModifier_adj = gtk_adjustment_new (2023, 1950, 2024, 1, 10, 10);
  GDyySpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (GDyySpinModifier_adj), 1, 0);
  gtk_widget_show (GDyySpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDyySpinModifier, 720, 344);
  gtk_widget_set_size_request (GDyySpinModifier, 60, 27);

  GDquantiteSpinModifier_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  GDquantiteSpinModifier = gtk_spin_button_new (GTK_ADJUSTMENT (GDquantiteSpinModifier_adj), 1, 0);
  gtk_widget_show (GDquantiteSpinModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDquantiteSpinModifier, 376, 200);
  gtk_widget_set_size_request (GDquantiteSpinModifier, 60, 27);

  label35 = gtk_label_new (_("Modifier Demande"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 344, 72);
  gtk_widget_set_size_request (label35, 300, 17);

  GDcontroleSaisiModifier = gtk_label_new ("");
  gtk_widget_show (GDcontroleSaisiModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDcontroleSaisiModifier, 320, 664);
  gtk_widget_set_size_request (GDcontroleSaisiModifier, 300, 25);

  GDtypeSangComboModifier1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (GDtypeSangComboModifier1);
  gtk_fixed_put (GTK_FIXED (fixed4), GDtypeSangComboModifier1, 296, 432);
  gtk_widget_set_size_request (GDtypeSangComboModifier1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("A+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("A-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("B+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("B-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("O+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("O-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("AB+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDtypeSangComboModifier1), _("AB-"));

  label40 = gtk_label_new (_("Quantit\303\251 de Poche"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed4), label40, 160, 200);
  gtk_widget_set_size_request (label40, 176, 24);

  GDnonUrgenceModifier = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (GDnonUrgenceModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDnonUrgenceModifier, 464, 528);
  gtk_widget_set_size_request (GDnonUrgenceModifier, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (GDnonUrgenceModifier), GDnonUrgenceModifier_group);
  GDnonUrgenceModifier_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (GDnonUrgenceModifier));

  GDouiUrgenceModifier = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (GDouiUrgenceModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDouiUrgenceModifier, 320, 528);
  gtk_widget_set_size_request (GDouiUrgenceModifier, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (GDouiUrgenceModifier), GDnonUrgenceModifier_group);
  GDnonUrgenceModifier_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (GDouiUrgenceModifier));

  label41 = gtk_label_new (_("Cas d'urgence :"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed4), label41, 160, 528);
  gtk_widget_set_size_request (label41, 120, 25);

  label42 = gtk_label_new (_("statut de la demande"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed4), label42, 168, 600);
  gtk_widget_set_size_request (label42, 160, 25);

  GDCoursStatusModifier = gtk_check_button_new_with_mnemonic (_("en cours"));
  gtk_widget_show (GDCoursStatusModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDCoursStatusModifier, 344, 600);
  gtk_widget_set_size_request (GDCoursStatusModifier, 118, 24);

  GDTraiteStatusModifier = gtk_check_button_new_with_mnemonic (_("trait\303\251"));
  gtk_widget_show (GDTraiteStatusModifier);
  gtk_fixed_put (GTK_FIXED (fixed4), GDTraiteStatusModifier, 480, 600);
  gtk_widget_set_size_request (GDTraiteStatusModifier, 118, 24);

  label39 = gtk_label_new (_("Type de Sang"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed4), label39, 176, 440);
  gtk_widget_set_size_request (label39, 100, 17);

  label34 = gtk_label_new (_("Date :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 192, 344);
  gtk_widget_set_size_request (label34, 64, 25);

  GDetabComboModifier1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (GDetabComboModifier1);
  gtk_fixed_put (GTK_FIXED (fixed4), GDetabComboModifier1, 344, 256);
  gtk_widget_set_size_request (GDetabComboModifier1, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboModifier1), _("etab1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboModifier1), _("etab2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboModifier1), _("etab3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboModifier1), _("etab4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDetabComboModifier1), _("etab5"));

  label30 = gtk_label_new (_("Etablissement"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 208, 256);
  gtk_widget_set_size_request (label30, 112, 25);

  GDannulerModifierButton = gtk_button_new ();
  gtk_widget_show (GDannulerModifierButton);
  gtk_fixed_put (GTK_FIXED (fixed4), GDannulerModifierButton, 208, 744);
  gtk_widget_set_size_request (GDannulerModifierButton, 219, 58);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (GDannulerModifierButton), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox11), label36, FALSE, FALSE, 0);

  GDModifierButton = gtk_button_new ();
  gtk_widget_show (GDModifierButton);
  gtk_fixed_put (GTK_FIXED (fixed4), GDModifierButton, 592, 744);
  gtk_widget_set_size_request (GDModifierButton, 219, 58);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (GDModifierButton), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox12), label37, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) GDnonUrgenceModifier, "toggled",
                    G_CALLBACK (on_GDnonUrgenceModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDouiUrgenceModifier, "toggled",
                    G_CALLBACK (on_GDouiUrgenceModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDCoursStatusModifier, "toggled",
                    G_CALLBACK (on_GDCoursStatusModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDTraiteStatusModifier, "toggled",
                    G_CALLBACK (on_GDTraiteStatusModifier_toggled),
                    NULL);
  g_signal_connect ((gpointer) GDannulerModifierButton, "clicked",
                    G_CALLBACK (on_GDannulerModifierButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDModifierButton, "clicked",
                    G_CALLBACK (on_GDModifierButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDmodife, GDmodife, "GDmodife");
  GLADE_HOOKUP_OBJECT (GDmodife, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (GDmodife, GDidEntryModifier, "GDidEntryModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, label29, "label29");
  GLADE_HOOKUP_OBJECT (GDmodife, label31, "label31");
  GLADE_HOOKUP_OBJECT (GDmodife, GDjjSpinModifier, "GDjjSpinModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDmmSpinModifier, "GDmmSpinModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, label32, "label32");
  GLADE_HOOKUP_OBJECT (GDmodife, label33, "label33");
  GLADE_HOOKUP_OBJECT (GDmodife, GDyySpinModifier, "GDyySpinModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDquantiteSpinModifier, "GDquantiteSpinModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, label35, "label35");
  GLADE_HOOKUP_OBJECT (GDmodife, GDcontroleSaisiModifier, "GDcontroleSaisiModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDtypeSangComboModifier1, "GDtypeSangComboModifier1");
  GLADE_HOOKUP_OBJECT (GDmodife, label40, "label40");
  GLADE_HOOKUP_OBJECT (GDmodife, GDnonUrgenceModifier, "GDnonUrgenceModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDouiUrgenceModifier, "GDouiUrgenceModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, label41, "label41");
  GLADE_HOOKUP_OBJECT (GDmodife, label42, "label42");
  GLADE_HOOKUP_OBJECT (GDmodife, GDCoursStatusModifier, "GDCoursStatusModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, GDTraiteStatusModifier, "GDTraiteStatusModifier");
  GLADE_HOOKUP_OBJECT (GDmodife, label39, "label39");
  GLADE_HOOKUP_OBJECT (GDmodife, label34, "label34");
  GLADE_HOOKUP_OBJECT (GDmodife, GDetabComboModifier1, "GDetabComboModifier1");
  GLADE_HOOKUP_OBJECT (GDmodife, label30, "label30");
  GLADE_HOOKUP_OBJECT (GDmodife, GDannulerModifierButton, "GDannulerModifierButton");
  GLADE_HOOKUP_OBJECT (GDmodife, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (GDmodife, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (GDmodife, image12, "image12");
  GLADE_HOOKUP_OBJECT (GDmodife, label36, "label36");
  GLADE_HOOKUP_OBJECT (GDmodife, GDModifierButton, "GDModifierButton");
  GLADE_HOOKUP_OBJECT (GDmodife, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (GDmodife, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (GDmodife, image13, "image13");
  GLADE_HOOKUP_OBJECT (GDmodife, label37, "label37");

  return GDmodife;
}

GtkWidget*
create_GDstatistique (void)
{
  GtkWidget *GDstatistique;
  GtkWidget *fixed5;
  GtkWidget *label49;
  GtkWidget *GDcomboEtabStatistique;
  GtkWidget *label43;
  GtkWidget *GDcontroleSaisiStatistique;
  GtkWidget *GDstatistiqueButton;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label50;
  GtkWidget *GDannulerStatistiqueButton;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label48;
  GtkWidget *label52;
  GtkWidget *label44;
  GtkWidget *GDtypePlusDemandeLabelStatistique;
  GtkWidget *GDstatistiqueButton1;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image17;
  GtkWidget *label51;
  GtkWidget *GDpourcentageDemandeLabelStatistique;

  GDstatistique = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GDstatistique), _("Statistique"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (GDstatistique), fixed5);
  gtk_widget_set_size_request (fixed5, 645, 393);

  label49 = gtk_label_new (_("Statistique"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed5), label49, 272, 48);
  gtk_widget_set_size_request (label49, 109, 17);

  GDcomboEtabStatistique = gtk_combo_box_entry_new_text ();
  gtk_widget_show (GDcomboEtabStatistique);
  gtk_fixed_put (GTK_FIXED (fixed5), GDcomboEtabStatistique, 256, 104);
  gtk_widget_set_size_request (GDcomboEtabStatistique, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDcomboEtabStatistique), _("etab1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDcomboEtabStatistique), _("etab2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDcomboEtabStatistique), _("etab3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDcomboEtabStatistique), _("etab4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (GDcomboEtabStatistique), _("etab5"));

  label43 = gtk_label_new (_("pourcentage du demande : "));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed5), label43, 80, 168);
  gtk_widget_set_size_request (label43, 202, 17);

  GDcontroleSaisiStatistique = gtk_label_new ("");
  gtk_widget_show (GDcontroleSaisiStatistique);
  gtk_fixed_put (GTK_FIXED (fixed5), GDcontroleSaisiStatistique, 480, 104);
  gtk_widget_set_size_request (GDcontroleSaisiStatistique, 161, 17);

  GDstatistiqueButton = gtk_button_new ();
  gtk_widget_show (GDstatistiqueButton);
  gtk_fixed_put (GTK_FIXED (fixed5), GDstatistiqueButton, 216, 344);
  gtk_widget_set_size_request (GDstatistiqueButton, 240, 44);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (GDstatistiqueButton), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-leave-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Type de sang le plus demand\303\251"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox15), label50, FALSE, FALSE, 0);

  GDannulerStatistiqueButton = gtk_button_new ();
  gtk_widget_show (GDannulerStatistiqueButton);
  gtk_fixed_put (GTK_FIXED (fixed5), GDannulerStatistiqueButton, 248, 424);
  gtk_widget_set_size_request (GDannulerStatistiqueButton, 168, 42);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (GDannulerStatistiqueButton), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox14), label48, FALSE, FALSE, 0);

  label52 = gtk_label_new (_("Etabalissement :"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed5), label52, 112, 112);
  gtk_widget_set_size_request (label52, 136, 17);

  label44 = gtk_label_new (_("Type de sang la plus demand\303\251 :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed5), label44, 72, 288);
  gtk_widget_set_size_request (label44, 232, 24);

  GDtypePlusDemandeLabelStatistique = gtk_label_new ("");
  gtk_widget_show (GDtypePlusDemandeLabelStatistique);
  gtk_fixed_put (GTK_FIXED (fixed5), GDtypePlusDemandeLabelStatistique, 312, 288);
  gtk_widget_set_size_request (GDtypePlusDemandeLabelStatistique, 56, 25);

  GDstatistiqueButton1 = gtk_button_new ();
  gtk_widget_show (GDstatistiqueButton1);
  gtk_fixed_put (GTK_FIXED (fixed5), GDstatistiqueButton1, 248, 216);
  gtk_widget_set_size_request (GDstatistiqueButton1, 192, 43);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (GDstatistiqueButton1), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image17 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox16), image17, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("pourcentage demande "));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox16), label51, FALSE, FALSE, 0);

  GDpourcentageDemandeLabelStatistique = gtk_label_new ("");
  gtk_widget_show (GDpourcentageDemandeLabelStatistique);
  gtk_fixed_put (GTK_FIXED (fixed5), GDpourcentageDemandeLabelStatistique, 296, 168);
  gtk_widget_set_size_request (GDpourcentageDemandeLabelStatistique, 56, 25);

  g_signal_connect ((gpointer) GDstatistiqueButton, "clicked",
                    G_CALLBACK (on_GDstatistiqueButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDannulerStatistiqueButton, "clicked",
                    G_CALLBACK (on_GDannulerStatistiqueButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) GDstatistiqueButton1, "clicked",
                    G_CALLBACK (on_GDstatistiqueButton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GDstatistique, GDstatistique, "GDstatistique");
  GLADE_HOOKUP_OBJECT (GDstatistique, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (GDstatistique, label49, "label49");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDcomboEtabStatistique, "GDcomboEtabStatistique");
  GLADE_HOOKUP_OBJECT (GDstatistique, label43, "label43");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDcontroleSaisiStatistique, "GDcontroleSaisiStatistique");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDstatistiqueButton, "GDstatistiqueButton");
  GLADE_HOOKUP_OBJECT (GDstatistique, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (GDstatistique, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (GDstatistique, image16, "image16");
  GLADE_HOOKUP_OBJECT (GDstatistique, label50, "label50");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDannulerStatistiqueButton, "GDannulerStatistiqueButton");
  GLADE_HOOKUP_OBJECT (GDstatistique, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (GDstatistique, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (GDstatistique, image15, "image15");
  GLADE_HOOKUP_OBJECT (GDstatistique, label48, "label48");
  GLADE_HOOKUP_OBJECT (GDstatistique, label52, "label52");
  GLADE_HOOKUP_OBJECT (GDstatistique, label44, "label44");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDtypePlusDemandeLabelStatistique, "GDtypePlusDemandeLabelStatistique");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDstatistiqueButton1, "GDstatistiqueButton1");
  GLADE_HOOKUP_OBJECT (GDstatistique, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (GDstatistique, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (GDstatistique, image17, "image17");
  GLADE_HOOKUP_OBJECT (GDstatistique, label51, "label51");
  GLADE_HOOKUP_OBJECT (GDstatistique, GDpourcentageDemandeLabelStatistique, "GDpourcentageDemandeLabelStatistique");

  return GDstatistique;
}


GtkWidget*
create_gestion_rdv (void)
{
  GtkWidget *gestion_rdv;
  GtkWidget *fixed1;
  GtkWidget *scrolle_theme;
  GtkWidget *viewport1;
  GtkWidget *fixed8;
  GtkWidget *theme1;
  GtkWidget *theme2;
  GtkWidget *theme_btn;
  GtkWidget *image10;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label10;
  GtkObject *S1_adj;
  GtkWidget *S1;
  GtkObject *S2_adj;
  GtkWidget *S2;
  GtkObject *S3_adj;
  GtkWidget *S3;
  GtkWidget *label16;
  GtkWidget *entryid;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkWidget *combo1;
  GtkWidget *comboA;
  GtkWidget *err_nom;
  GtkWidget *err_prenom;
  GtkWidget *EXIT_ranim;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label19;
  GtkWidget *ajouter_ranim;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label18;
  GtkWidget *err_cin;
  GtkWidget *valid_msg;
  GtkWidget *R1;
  GSList *R1_group = NULL;
  GtkWidget *R2;
  GtkWidget *label13;
  GtkWidget *combo2;
  GtkWidget *label9;
  GtkWidget *label6;
  GtkWidget *label14;
  GtkWidget *label17;
  GtkWidget *label15;
  GtkWidget *label11;
  GtkWidget *label1;
  GtkWidget *fixed3;
  GtkWidget *id_modif;
  GtkObject *S4_adj;
  GtkWidget *S4;
  GtkObject *S5_adj;
  GtkWidget *S5;
  GtkObject *S6_adj;
  GtkWidget *S6;
  GtkWidget *label22;
  GtkWidget *label24;
  GtkWidget *label20;
  GtkWidget *label27;
  GtkWidget *label25;
  GtkWidget *label23;
  GtkWidget *combo4;
  GtkWidget *label21;
  GtkWidget *combo3;
  GtkWidget *modif;
  GtkWidget *B4;
  GtkWidget *image3;
  GtkWidget *label26;
  GtkWidget *R3;
  GSList *R3_group = NULL;
  GtkWidget *R4;
  GtkWidget *B5;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label28;
  GtkWidget *modif1;
  GtkWidget *label2;
  GtkWidget *fixed4;
  GtkWidget *is;
  GtkWidget *label29;
  GtkWidget *supp_rann;
  GtkWidget *image5;
  GtkWidget *L1;
  GtkWidget *label3;
  GtkWidget *fixed6;
  GtkWidget *histo_win_disp;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label40;
  GtkWidget *statistique_btn;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image9;
  GtkWidget *label41;
  GtkWidget *label12;
  GtkWidget *titreranim;

  gestion_rdv = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_rdv, 1146, 744);
  gtk_window_set_title (GTK_WINDOW (gestion_rdv), _("window1"));
  gtk_window_set_resizable (GTK_WINDOW (gestion_rdv), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestion_rdv), fixed1);

  scrolle_theme = gtk_scrolled_window_new (NULL, NULL);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolle_theme, 936, 56);
  gtk_widget_set_size_request (scrolle_theme, 128, 104);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolle_theme), viewport1);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed8);

  theme1 = gtk_check_button_new_with_mnemonic (_("image 1"));
  gtk_widget_show (theme1);
  gtk_fixed_put (GTK_FIXED (fixed8), theme1, 8, 16);
  gtk_widget_set_size_request (theme1, 118, 24);

  theme2 = gtk_check_button_new_with_mnemonic (_("image 2"));
  gtk_widget_show (theme2);
  gtk_fixed_put (GTK_FIXED (fixed8), theme2, 8, 48);
  gtk_widget_set_size_request (theme2, 118, 24);

  theme_btn = gtk_button_new ();
  gtk_widget_show (theme_btn);
  gtk_fixed_put (GTK_FIXED (fixed1), theme_btn, 1048, 32);
  gtk_widget_set_size_request (theme_btn, 40, 32);

  image10 = gtk_image_new_from_stock ("gtk-select-color", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (theme_btn), image10);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 152, 64);
  gtk_widget_set_size_request (notebook1, 870, 648);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  label7 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='13'> *Nom :  </span>"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 64, 112);
  gtk_widget_set_size_request (label7, 80, 32);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  label8 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='13'> *Pr\303\251nom : </span>"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 64, 160);
  gtk_widget_set_size_request (label8, 112, 48);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  label10 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='13'> *R\303\251gion :  </span>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 56, 336);
  gtk_widget_set_size_request (label10, 104, 48);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  S1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  S1 = gtk_spin_button_new (GTK_ADJUSTMENT (S1_adj), 1, 0);
  gtk_widget_show (S1);
  gtk_fixed_put (GTK_FIXED (fixed2), S1, 232, 232);
  gtk_widget_set_size_request (S1, 60, 27);

  S2_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  S2 = gtk_spin_button_new (GTK_ADJUSTMENT (S2_adj), 1, 0);
  gtk_widget_show (S2);
  gtk_fixed_put (GTK_FIXED (fixed2), S2, 392, 232);
  gtk_widget_set_size_request (S2, 60, 27);

  S3_adj = gtk_adjustment_new (1, 1000, 3000, 1, 10, 10);
  S3 = gtk_spin_button_new (GTK_ADJUSTMENT (S3_adj), 1, 0);
  gtk_widget_show (S3);
  gtk_fixed_put (GTK_FIXED (fixed2), S3, 552, 232);
  gtk_widget_set_size_request (S3, 60, 27);

  label16 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='13'> *Type de sang  : </span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 64, 408);
  gtk_widget_set_size_request (label16, 144, 40);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed2), entryid, 176, 64);
  gtk_widget_set_size_request (entryid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed2), nom, 176, 120);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), prenom, 176, 168);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  combo1 = gtk_combo_box_new_text ();
  gtk_widget_show (combo1);
  gtk_fixed_put (GTK_FIXED (fixed2), combo1, 224, 344);
  gtk_widget_set_size_request (combo1, 120, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("b\303\251ja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("ben arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("gab\303\251s"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("gafsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("k\303\251bili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("kef"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("m\303\251dnine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("sid bouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("siliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("tatouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), _("zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo1), "");

  comboA = gtk_combo_box_new_text ();
  gtk_widget_show (comboA);
  gtk_fixed_put (GTK_FIXED (fixed2), comboA, 224, 408);
  gtk_widget_set_size_request (comboA, 120, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboA), _("A+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboA), _("A-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboA), _("B+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboA), _("B-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboA), _("O+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboA), _("O-"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboA), _("AB+"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboA), _("AB-"));

  err_nom = gtk_label_new ("");
  gtk_widget_show (err_nom);
  gtk_fixed_put (GTK_FIXED (fixed2), err_nom, 360, 128);
  gtk_widget_set_size_request (err_nom, 176, 17);

  err_prenom = gtk_label_new ("");
  gtk_widget_show (err_prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), err_prenom, 360, 177);
  gtk_widget_set_size_request (err_prenom, 176, 16);

  EXIT_ranim = gtk_button_new ();
  gtk_widget_show (EXIT_ranim);
  gtk_fixed_put (GTK_FIXED (fixed2), EXIT_ranim, 664, 144);
  gtk_widget_set_size_request (EXIT_ranim, 160, 64);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (EXIT_ranim), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("<span weight='bold' foreground='#A52A2A' font='13'> D\303\251connexion  </span>"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox2), label19, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  ajouter_ranim = gtk_button_new ();
  gtk_widget_show (ajouter_ranim);
  gtk_fixed_put (GTK_FIXED (fixed2), ajouter_ranim, 664, 280);
  gtk_widget_set_size_request (ajouter_ranim, 162, 53);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter_ranim), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("<span weight='bold' foreground='#A52A2A' font='15'> Ajouter  </span>"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox1), label18, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  err_cin = gtk_label_new ("");
  gtk_widget_show (err_cin);
  gtk_fixed_put (GTK_FIXED (fixed2), err_cin, 360, 64);
  gtk_widget_set_size_request (err_cin, 176, 16);
  gtk_misc_set_alignment (GTK_MISC (err_cin), 0.4, 0.5);

  valid_msg = gtk_label_new ("");
  gtk_widget_show (valid_msg);
  gtk_fixed_put (GTK_FIXED (fixed2), valid_msg, 680, 352);
  gtk_widget_set_size_request (valid_msg, 152, 16);

  R1 = gtk_radio_button_new_with_mnemonic (NULL, _("matin"));
  gtk_widget_show (R1);
  gtk_fixed_put (GTK_FIXED (fixed2), R1, 312, 480);
  gtk_widget_set_size_request (R1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (R1), R1_group);
  R1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (R1));

  R2 = gtk_radio_button_new_with_mnemonic (NULL, _("apr\303\251s-midi"));
  gtk_widget_show (R2);
  gtk_fixed_put (GTK_FIXED (fixed2), R2, 440, 480);
  gtk_widget_set_size_request (R2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (R2), R1_group);
  R1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (R2));

  label13 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='13'> *P\303\251riode de Pr\303\251l\303\251vement  : </span>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 48, 464);
  gtk_widget_set_size_request (label13, 240, 56);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  combo2 = gtk_combo_box_new_text ();
  gtk_widget_show (combo2);
  gtk_fixed_put (GTK_FIXED (fixed2), combo2, 456, 340);
  gtk_widget_set_size_request (combo2, 126, 37);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo2), _("ETS1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo2), _("ETS2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo2), _("ETS3"));

  label9 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='13'> *Date  : </span>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 56, 224);
  gtk_widget_set_size_request (label9, 104, 48);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  label6 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='13'> *CIN : </span>"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 56, 56);
  gtk_widget_set_size_request (label6, 88, 32);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  label14 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='13'>* Jour : </span>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 152, 224);
  gtk_widget_set_size_request (label14, 80, 41);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label17 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='13'>* mois : </span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 304, 224);
  gtk_widget_set_size_request (label17, 88, 41);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label15 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='13'>* ann\303\251e : </span>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 448, 224);
  gtk_widget_set_size_request (label15, 120, 41);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label11 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='13'> *ETS  : </span>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 368, 336);
  gtk_widget_set_size_request (label11, 80, 40);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  label1 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='15'> Ajouter </span>"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);
  gtk_widget_set_size_request (label1, 209, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  id_modif = gtk_entry_new ();
  gtk_widget_show (id_modif);
  gtk_fixed_put (GTK_FIXED (fixed3), id_modif, 304, 48);
  gtk_widget_set_size_request (id_modif, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_modif), 8226);

  S4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  S4 = gtk_spin_button_new (GTK_ADJUSTMENT (S4_adj), 1, 0);
  gtk_widget_show (S4);
  gtk_fixed_put (GTK_FIXED (fixed3), S4, 328, 168);
  gtk_widget_set_size_request (S4, 60, 27);

  S5_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  S5 = gtk_spin_button_new (GTK_ADJUSTMENT (S5_adj), 1, 0);
  gtk_widget_show (S5);
  gtk_fixed_put (GTK_FIXED (fixed3), S5, 512, 168);
  gtk_widget_set_size_request (S5, 60, 27);

  S6_adj = gtk_adjustment_new (1, 1000, 3000, 1, 10, 10);
  S6 = gtk_spin_button_new (GTK_ADJUSTMENT (S6_adj), 1, 0);
  gtk_widget_show (S6);
  gtk_fixed_put (GTK_FIXED (fixed3), S6, 696, 168);
  gtk_widget_set_size_request (S6, 79, 27);

  label22 = gtk_label_new (_("<span weight='bold' foreground='#000' font='13'>* Jour : </span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 240, 168);
  gtk_widget_set_size_request (label22, 88, 32);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label24 = gtk_label_new (_("<span weight='bold' foreground='#0000' font='13'>* Ann\303\251e : </span>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 600, 160);
  gtk_widget_set_size_request (label24, 96, 41);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label20 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='14'>* CIN: </span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 240, 48);
  gtk_widget_set_size_request (label20, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  label27 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='14'>* r\303\251gion : </span>"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed3), label27, 512, 264);
  gtk_widget_set_size_request (label27, 112, 33);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label25 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='14'>* ETS :</span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed3), label25, 56, 264);
  gtk_widget_set_size_request (label25, 64, 32);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label23 = gtk_label_new (_("<span weight='bold' foreground='#000' font='13'>* mois : </span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 424, 168);
  gtk_widget_set_size_request (label23, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  combo4 = gtk_combo_box_new_text ();
  gtk_widget_show (combo4);
  gtk_fixed_put (GTK_FIXED (fixed3), combo4, 632, 264);
  gtk_widget_set_size_request (combo4, 120, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("b\303\251ja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("ben arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("gab\303\251s"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("gafsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("kairouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("kasserine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("k\303\251bili"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("kef"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("m\303\251dnine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("sid bouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("siliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("tatouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), _("zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo4), "");

  label21 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='14'>* Nouvelle Date : </span>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 48, 160);
  gtk_widget_set_size_request (label21, 152, 41);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  combo3 = gtk_combo_box_new_text ();
  gtk_widget_show (combo3);
  gtk_fixed_put (GTK_FIXED (fixed3), combo3, 144, 264);
  gtk_widget_set_size_request (combo3, 129, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo3), _("ETS1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo3), _("ETS2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo3), _("ETS3"));

  modif = gtk_label_new ("");
  gtk_widget_show (modif);
  gtk_fixed_put (GTK_FIXED (fixed3), modif, 240, 96);
  gtk_widget_set_size_request (modif, 336, 48);

  B4 = gtk_button_new ();
  gtk_widget_show (B4);
  gtk_fixed_put (GTK_FIXED (fixed3), B4, 480, 48);
  gtk_widget_set_size_request (B4, 48, 37);

  image3 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (B4), image3);

  label26 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='13'>* P\303\251riode de pr\303\251levement  : </span>"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed3), label26, 40, 360);
  gtk_widget_set_size_request (label26, 233, 49);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  R3 = gtk_radio_button_new_with_mnemonic (NULL, _("matin"));
  gtk_widget_show (R3);
  gtk_fixed_put (GTK_FIXED (fixed3), R3, 304, 368);
  gtk_widget_set_size_request (R3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (R3), R3_group);
  R3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (R3));

  R4 = gtk_radio_button_new_with_mnemonic (NULL, _("apr\303\251s-midi"));
  gtk_widget_show (R4);
  gtk_fixed_put (GTK_FIXED (fixed3), R4, 440, 368);
  gtk_widget_set_size_request (R4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (R4), R3_group);
  R3_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (R4));

  B5 = gtk_button_new ();
  gtk_widget_show (B5);
  gtk_fixed_put (GTK_FIXED (fixed3), B5, 400, 440);
  gtk_widget_set_size_request (B5, 112, 49);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (B5), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("<span weight='bold' foreground='#000' font='13'>Valider </span>"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox3), label28, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  modif1 = gtk_label_new ("");
  gtk_widget_show (modif1);
  gtk_fixed_put (GTK_FIXED (fixed3), modif1, 264, 496);
  gtk_widget_set_size_request (modif1, 408, 41);

  label2 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='15'> Modifier </span>"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);
  gtk_widget_set_size_request (label2, 210, 68);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  is = gtk_entry_new ();
  gtk_widget_show (is);
  gtk_fixed_put (GTK_FIXED (fixed4), is, 336, 104);
  gtk_widget_set_size_request (is, 200, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (is), 8226);

  label29 = gtk_label_new (_("<span weight='bold' foreground='#000' font='13'>* CIN :</span>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 256, 112);
  gtk_widget_set_size_request (label29, 72, 24);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  supp_rann = gtk_button_new ();
  gtk_widget_show (supp_rann);
  gtk_fixed_put (GTK_FIXED (fixed4), supp_rann, 544, 104);
  gtk_widget_set_size_request (supp_rann, 40, 32);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (supp_rann), image5);

  L1 = gtk_label_new ("");
  gtk_widget_show (L1);
  gtk_fixed_put (GTK_FIXED (fixed4), L1, 248, 160);
  gtk_widget_set_size_request (L1, 392, 48);

  label3 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='15'> Supprimer</span>"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);
  gtk_widget_set_size_request (label3, 206, 68);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  histo_win_disp = gtk_button_new ();
  gtk_widget_show (histo_win_disp);
  gtk_fixed_put (GTK_FIXED (fixed6), histo_win_disp, 352, 88);
  gtk_widget_set_size_request (histo_win_disp, 232, 80);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (histo_win_disp), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("<span weight='bold' foreground='#000' font='15'> Historique </span>"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox6), label40, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  statistique_btn = gtk_button_new ();
  gtk_widget_show (statistique_btn);
  gtk_fixed_put (GTK_FIXED (fixed6), statistique_btn, 352, 192);
  gtk_widget_set_size_request (statistique_btn, 232, 85);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (statistique_btn), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image9 = gtk_image_new_from_stock ("gtk-page-setup", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox7), image9, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("<span weight='bold' foreground='#000' font='15'> Statistiques </span>"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox7), label41, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  label12 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='15'> Menu </span>"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label12);
  gtk_widget_set_size_request (label12, 198, -1);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  titreranim = gtk_label_new ("");
  gtk_widget_show (titreranim);
  gtk_fixed_put (GTK_FIXED (fixed1), titreranim, 384, 16);
  gtk_widget_set_size_request (titreranim, 400, 56);

  g_signal_connect ((gpointer) theme1, "toggled",
                    G_CALLBACK (on_theme1_toggled),
                    NULL);
  g_signal_connect_swapped ((gpointer) theme1, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (scrolle_theme));
  g_signal_connect_swapped ((gpointer) theme1, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (gestion_rdv));
  g_signal_connect ((gpointer) theme2, "toggled",
                    G_CALLBACK (on_theme2_toggled),
                    NULL);
  g_signal_connect_swapped ((gpointer) theme2, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (scrolle_theme));
  g_signal_connect_swapped ((gpointer) theme2, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (gestion_rdv));
  g_signal_connect_swapped ((gpointer) theme_btn, "clicked",
                            G_CALLBACK (gtk_widget_show),
                            GTK_OBJECT (scrolle_theme));
  g_signal_connect ((gpointer) theme_btn, "clicked",
                    G_CALLBACK (on_theme_btn_clicked),
                    NULL);
  g_signal_connect ((gpointer) EXIT_ranim, "clicked",
                    G_CALLBACK (on_EXIT_ranim_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_ranim, "clicked",
                    G_CALLBACK (on_ajouter_ranim_clicked),
                    NULL);
  g_signal_connect ((gpointer) R1, "toggled",
                    G_CALLBACK (on_R1_toggled),
                    NULL);
  g_signal_connect ((gpointer) R2, "toggled",
                    G_CALLBACK (on_R2_toggled),
                    NULL);
  g_signal_connect ((gpointer) B4, "clicked",
                    G_CALLBACK (on_B4_clicked),
                    NULL);
  g_signal_connect ((gpointer) R3, "toggled",
                    G_CALLBACK (on_R3_toggled),
                    NULL);
  g_signal_connect ((gpointer) R4, "toggled",
                    G_CALLBACK (on_R4_toggled),
                    NULL);
  g_signal_connect ((gpointer) B5, "clicked",
                    G_CALLBACK (on_B5_clicked),
                    NULL);
  g_signal_connect ((gpointer) supp_rann, "clicked",
                    G_CALLBACK (on_supp_rann_clicked),
                    NULL);
  g_signal_connect ((gpointer) histo_win_disp, "clicked",
                    G_CALLBACK (on_histo_win_disp_clicked),
                    NULL);
  g_signal_connect ((gpointer) statistique_btn, "clicked",
                    G_CALLBACK (on_statistique_btn_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_rdv, gestion_rdv, "gestion_rdv");
  GLADE_HOOKUP_OBJECT (gestion_rdv, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, scrolle_theme, "scrolle_theme");
  GLADE_HOOKUP_OBJECT (gestion_rdv, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (gestion_rdv, theme1, "theme1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, theme2, "theme2");
  GLADE_HOOKUP_OBJECT (gestion_rdv, theme_btn, "theme_btn");
  GLADE_HOOKUP_OBJECT (gestion_rdv, image10, "image10");
  GLADE_HOOKUP_OBJECT (gestion_rdv, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label8, "label8");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label10, "label10");
  GLADE_HOOKUP_OBJECT (gestion_rdv, S1, "S1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, S2, "S2");
  GLADE_HOOKUP_OBJECT (gestion_rdv, S3, "S3");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion_rdv, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (gestion_rdv, nom, "nom");
  GLADE_HOOKUP_OBJECT (gestion_rdv, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (gestion_rdv, combo1, "combo1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, comboA, "comboA");
  GLADE_HOOKUP_OBJECT (gestion_rdv, err_nom, "err_nom");
  GLADE_HOOKUP_OBJECT (gestion_rdv, err_prenom, "err_prenom");
  GLADE_HOOKUP_OBJECT (gestion_rdv, EXIT_ranim, "EXIT_ranim");
  GLADE_HOOKUP_OBJECT (gestion_rdv, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_rdv, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_rdv, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion_rdv, ajouter_ranim, "ajouter_ranim");
  GLADE_HOOKUP_OBJECT (gestion_rdv, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, image1, "image1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion_rdv, err_cin, "err_cin");
  GLADE_HOOKUP_OBJECT (gestion_rdv, valid_msg, "valid_msg");
  GLADE_HOOKUP_OBJECT (gestion_rdv, R1, "R1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, R2, "R2");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestion_rdv, combo2, "combo2");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label9, "label9");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label6, "label6");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label15, "label15");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label11, "label11");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label1, "label1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion_rdv, id_modif, "id_modif");
  GLADE_HOOKUP_OBJECT (gestion_rdv, S4, "S4");
  GLADE_HOOKUP_OBJECT (gestion_rdv, S5, "S5");
  GLADE_HOOKUP_OBJECT (gestion_rdv, S6, "S6");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label22, "label22");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label24, "label24");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label23, "label23");
  GLADE_HOOKUP_OBJECT (gestion_rdv, combo4, "combo4");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion_rdv, combo3, "combo3");
  GLADE_HOOKUP_OBJECT (gestion_rdv, modif, "modif");
  GLADE_HOOKUP_OBJECT (gestion_rdv, B4, "B4");
  GLADE_HOOKUP_OBJECT (gestion_rdv, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label26, "label26");
  GLADE_HOOKUP_OBJECT (gestion_rdv, R3, "R3");
  GLADE_HOOKUP_OBJECT (gestion_rdv, R4, "R4");
  GLADE_HOOKUP_OBJECT (gestion_rdv, B5, "B5");
  GLADE_HOOKUP_OBJECT (gestion_rdv, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_rdv, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_rdv, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label28, "label28");
  GLADE_HOOKUP_OBJECT (gestion_rdv, modif1, "modif1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label2, "label2");
  GLADE_HOOKUP_OBJECT (gestion_rdv, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_rdv, is, "is");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label29, "label29");
  GLADE_HOOKUP_OBJECT (gestion_rdv, supp_rann, "supp_rann");
  GLADE_HOOKUP_OBJECT (gestion_rdv, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_rdv, L1, "L1");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion_rdv, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (gestion_rdv, histo_win_disp, "histo_win_disp");
  GLADE_HOOKUP_OBJECT (gestion_rdv, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_rdv, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_rdv, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label40, "label40");
  GLADE_HOOKUP_OBJECT (gestion_rdv, statistique_btn, "statistique_btn");
  GLADE_HOOKUP_OBJECT (gestion_rdv, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_rdv, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_rdv, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label41, "label41");
  GLADE_HOOKUP_OBJECT (gestion_rdv, label12, "label12");
  GLADE_HOOKUP_OBJECT (gestion_rdv, titreranim, "titreranim");

  return gestion_rdv;
}

GtkWidget*
create_window_historique (void)
{
  GtkWidget *window_historique;
  GtkWidget *fixed7;
  GtkWidget *scrolledwindow3;
  GtkWidget *historique;
  GtkWidget *res_rdv_input;
  GtkWidget *button_res_rdv;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label39;
  GtkWidget *aff_his;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label37;
  GtkWidget *label38;

  window_historique = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_historique, 916, 585);
  gtk_window_set_title (GTK_WINDOW (window_historique), _("window1"));
  gtk_window_set_resizable (GTK_WINDOW (window_historique), FALSE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window_historique), fixed7);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed7), scrolledwindow3, 232, 48);
  gtk_widget_set_size_request (scrolledwindow3, 608, 480);

  historique = gtk_tree_view_new ();
  gtk_widget_show (historique);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), historique);
  gtk_widget_set_size_request (historique, 390, 209);

  res_rdv_input = gtk_entry_new ();
  gtk_widget_show (res_rdv_input);
  gtk_fixed_put (GTK_FIXED (fixed7), res_rdv_input, 40, 72);
  gtk_widget_set_size_request (res_rdv_input, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (res_rdv_input), 8226);

  button_res_rdv = gtk_button_new ();
  gtk_widget_show (button_res_rdv);
  gtk_fixed_put (GTK_FIXED (fixed7), button_res_rdv, 48, 160);
  gtk_widget_set_size_request (button_res_rdv, 144, 64);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_res_rdv), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("<span weight='bold' foreground='#000' font='13'> Chercher </span>"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox5), label39, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  aff_his = gtk_button_new ();
  gtk_widget_show (aff_his);
  gtk_fixed_put (GTK_FIXED (fixed7), aff_his, 48, 240);
  gtk_widget_set_size_request (aff_his, 144, 64);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (aff_his), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("<span weight='bold' foreground='#000' font='13'> Afficher </span>"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox4), label37, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label38 = gtk_label_new (_("<span weight='bold' foreground='#000' font='10'> Chercher Par CIN : </span>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed7), label38, 24, 40);
  gtk_widget_set_size_request (label38, 152, 25);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  g_signal_connect ((gpointer) historique, "row_activated",
                    G_CALLBACK (on_historique_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_res_rdv, "clicked",
                    G_CALLBACK (on_button_res_rdv_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) button_res_rdv, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (window_historique));
  g_signal_connect ((gpointer) aff_his, "clicked",
                    G_CALLBACK (on_aff_his_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) aff_his, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (window_historique));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_historique, window_historique, "window_historique");
  GLADE_HOOKUP_OBJECT (window_historique, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window_historique, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window_historique, historique, "historique");
  GLADE_HOOKUP_OBJECT (window_historique, res_rdv_input, "res_rdv_input");
  GLADE_HOOKUP_OBJECT (window_historique, button_res_rdv, "button_res_rdv");
  GLADE_HOOKUP_OBJECT (window_historique, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_historique, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window_historique, image7, "image7");
  GLADE_HOOKUP_OBJECT (window_historique, label39, "label39");
  GLADE_HOOKUP_OBJECT (window_historique, aff_his, "aff_his");
  GLADE_HOOKUP_OBJECT (window_historique, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_historique, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_historique, image6, "image6");
  GLADE_HOOKUP_OBJECT (window_historique, label37, "label37");
  GLADE_HOOKUP_OBJECT (window_historique, label38, "label38");

  return window_historique;
}

GtkWidget*
create_window_statistique (void)
{
  GtkWidget *window_statistique;
  GtkWidget *fixed9;
  GtkObject *SSJ1_adj;
  GtkWidget *SSJ1;
  GtkObject *SSA3_adj;
  GtkWidget *SSA3;
  GtkObject *SSM2_adj;
  GtkWidget *SSM2;
  GtkWidget *label57;
  GtkWidget *label56;
  GtkWidget *label54;
  GtkWidget *entrycapacite;
  GtkWidget *label60;
  GtkWidget *radiostat2;
  GSList *radiostat2_group = NULL;
  GtkWidget *radiostat1;
  GtkWidget *label59;
  GtkWidget *label58;
  GtkWidget *label53;
  GtkWidget *comboets;
  GtkWidget *B10;
  GtkWidget *image11;
  GtkWidget *label55;
  GtkWidget *result_ran;

  window_statistique = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_statistique), _("window1"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window_statistique), fixed9);

  SSJ1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  SSJ1 = gtk_spin_button_new (GTK_ADJUSTMENT (SSJ1_adj), 1, 0);
  gtk_widget_show (SSJ1);
  gtk_fixed_put (GTK_FIXED (fixed9), SSJ1, 136, 56);
  gtk_widget_set_size_request (SSJ1, 60, 27);

  SSA3_adj = gtk_adjustment_new (1, 1000, 3000, 1, 10, 10);
  SSA3 = gtk_spin_button_new (GTK_ADJUSTMENT (SSA3_adj), 1, 0);
  gtk_widget_show (SSA3);
  gtk_fixed_put (GTK_FIXED (fixed9), SSA3, 136, 168);
  gtk_widget_set_size_request (SSA3, 60, 27);

  SSM2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  SSM2 = gtk_spin_button_new (GTK_ADJUSTMENT (SSM2_adj), 1, 0);
  gtk_widget_show (SSM2);
  gtk_fixed_put (GTK_FIXED (fixed9), SSM2, 136, 112);
  gtk_widget_set_size_request (SSM2, 60, 27);

  label57 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='13'>* ann\303\251e : </span>"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed9), label57, 24, 160);
  gtk_widget_set_size_request (label57, 120, 41);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);

  label56 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='13'>* mois : </span>"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed9), label56, 32, 104);
  gtk_widget_set_size_request (label56, 88, 41);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  label54 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='13'> *Date  : </span>"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed9), label54, 8, 0);
  gtk_widget_set_size_request (label54, 104, 48);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  entrycapacite = gtk_entry_new ();
  gtk_widget_show (entrycapacite);
  gtk_fixed_put (GTK_FIXED (fixed9), entrycapacite, 376, 16);
  gtk_widget_set_size_request (entrycapacite, 128, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycapacite), 8226);

  label60 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='10'> Nb RDV : </span>"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed9), label60, 48, 264);
  gtk_widget_set_size_request (label60, 73, 25);
  gtk_label_set_use_markup (GTK_LABEL (label60), TRUE);

  radiostat2 = gtk_radio_button_new_with_mnemonic (NULL, _("apr\303\251s-midi"));
  gtk_widget_show (radiostat2);
  gtk_fixed_put (GTK_FIXED (fixed9), radiostat2, 376, 152);
  gtk_widget_set_size_request (radiostat2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiostat2), radiostat2_group);
  radiostat2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiostat2));

  radiostat1 = gtk_radio_button_new_with_mnemonic (NULL, _("matin"));
  gtk_widget_show (radiostat1);
  gtk_fixed_put (GTK_FIXED (fixed9), radiostat1, 376, 128);
  gtk_widget_set_size_request (radiostat1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiostat1), radiostat2_group);
  radiostat2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiostat1));

  label59 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='12'> *Capacit\303\251  : </span>"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed9), label59, 240, 8);
  gtk_widget_set_size_request (label59, 104, 48);
  gtk_label_set_use_markup (GTK_LABEL (label59), TRUE);

  label58 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='12'> *ETS  : </span>"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed9), label58, 240, 56);
  gtk_widget_set_size_request (label58, 80, 40);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  label53 = gtk_label_new (_("<span weight='bold' foreground='#000000' font='12'> *P\303\251riode  : </span>"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed9), label53, 176, 104);
  gtk_widget_set_size_request (label53, 240, 56);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  comboets = gtk_combo_box_new_text ();
  gtk_widget_show (comboets);
  gtk_fixed_put (GTK_FIXED (fixed9), comboets, 376, 56);
  gtk_widget_set_size_request (comboets, 126, 37);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboets), _("ETS1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboets), _("ETS2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboets), _("ETS3"));

  B10 = gtk_button_new ();
  gtk_widget_show (B10);
  gtk_fixed_put (GTK_FIXED (fixed9), B10, 224, 336);
  gtk_widget_set_size_request (B10, 48, 48);

  image11 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_container_add (GTK_CONTAINER (B10), image11);

  label55 = gtk_label_new (_("<span weight='bold' foreground='#A52A2A' font='13'>* Jour : </span>"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed9), label55, 32, 48);
  gtk_widget_set_size_request (label55, 80, 41);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  result_ran = gtk_label_new ("");
  gtk_widget_show (result_ran);
  gtk_fixed_put (GTK_FIXED (fixed9), result_ran, 120, 264);
  gtk_widget_set_size_request (result_ran, 72, 24);

  g_signal_connect ((gpointer) radiostat2, "toggled",
                    G_CALLBACK (on_radiostat2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiostat1, "toggled",
                    G_CALLBACK (on_radiostat1_toggled),
                    NULL);
  g_signal_connect ((gpointer) B10, "clicked",
                    G_CALLBACK (on_B10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_statistique, window_statistique, "window_statistique");
  GLADE_HOOKUP_OBJECT (window_statistique, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window_statistique, SSJ1, "SSJ1");
  GLADE_HOOKUP_OBJECT (window_statistique, SSA3, "SSA3");
  GLADE_HOOKUP_OBJECT (window_statistique, SSM2, "SSM2");
  GLADE_HOOKUP_OBJECT (window_statistique, label57, "label57");
  GLADE_HOOKUP_OBJECT (window_statistique, label56, "label56");
  GLADE_HOOKUP_OBJECT (window_statistique, label54, "label54");
  GLADE_HOOKUP_OBJECT (window_statistique, entrycapacite, "entrycapacite");
  GLADE_HOOKUP_OBJECT (window_statistique, label60, "label60");
  GLADE_HOOKUP_OBJECT (window_statistique, radiostat2, "radiostat2");
  GLADE_HOOKUP_OBJECT (window_statistique, radiostat1, "radiostat1");
  GLADE_HOOKUP_OBJECT (window_statistique, label59, "label59");
  GLADE_HOOKUP_OBJECT (window_statistique, label58, "label58");
  GLADE_HOOKUP_OBJECT (window_statistique, label53, "label53");
  GLADE_HOOKUP_OBJECT (window_statistique, comboets, "comboets");
  GLADE_HOOKUP_OBJECT (window_statistique, B10, "B10");
  GLADE_HOOKUP_OBJECT (window_statistique, image11, "image11");
  GLADE_HOOKUP_OBJECT (window_statistique, label55, "label55");
  GLADE_HOOKUP_OBJECT (window_statistique, result_ran, "result_ran");

  return window_statistique;
}

