/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *GDaffiche;
  gtk_init (&argc, &argv);
  GtkWidget *window1=gtk_window_new(GTK_WINDOW_TOPLEVEL);

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();


  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  GDaffiche = create_GDaffiche ();
  gtk_widget_show (GDaffiche);

  window1 = create_gestion_rdv ();
  gtk_widget_show (window1);

  chang_background(window1,750,520,"B.jpg");

  gtk_main ();
  return 0;
}

